on:
  push:
    branchs: [main]

jobs:
  Deploy:
    name: Deploy 
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: build app
        run: ./scripts/buildprod.sh

      - name: set up cloud sdk
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          version: '>= 363.0.0'

      - name: Submit docker
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-430415/notely-ar-repo




