name ci

on:
  pull_request
    branches: [main]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Set up Go
      users: actions/setup-go@v4
      with:
        go-version: '1.20'


